[package]
name = "zstd-framed"
version = "0.1.0"
edition = "2021"

[features]
default = ["futures", "tokio"]

[dependencies]
futures = { version = "0.3.31", optional = true }
pin-project-lite = "0.2.15"
thiserror = "1.0.68"
tokio = { version = "1.41.0", optional = true }
zstd = "0.13.2"
